### PR TITLE
Refactor the scene structure of the project

### PR DESCRIPTION
**Pull request by ghost**
As per issue #18 

Sorry, I got a bit carried away with my commit, so it's pretty bulky. Will make sure subsequent commits are broken down better.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good to me, and it works with current godot-git.

**Comment by akien-mga** [comment]
Thanks a lot :)

**Comment by ghost** [comment]
No problem at all :)

Just responding to your points:
- No preference either between `get_tree().get_root()` and `get_node("/root")`. In saying that, we probably should stick to one way of doing it, and `get_node("/root")` would make for less typing, especially when you need to jump through many levels of nodes:

`get_tree().get_root().get_node("child/child/child")` vs `get_node("/root/child/child/child")`

Up to you though :)
- You're right for calling me out on deleting the final line break, I had no idea that was a thing. Will keep it in mind for next time!

**Comment by akien-mga** [comment]
> No preference either between get_tree().get_root() and get_node("/root"). In saying that, we probably should stick to one way of doing it, and get_node("/root") would make for less typing, especially when you need to jump through many levels of nodes:

Yes, I personally went for `get_node("/root")` because it makes for less encapsulation; after playing around with VBA during an internship, I'm not so fond of overly encapsulated APIs :P 

Let's go with `get_node("/root")` then, since as you say it can also be easily extended to `get_node("/root/child")` if need be. Keeping lines short is especially important in a language where indentation is done with tabs IMO, as it's hard to align stuff properly on several lines :)

**Comment by ghost** [comment]
Sounds good. I'll make the format change on my next commit :)

**Pull request merged**
